services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ims_laravel
    container_name: ims_laravel
    ports:
      - "8000:8000"  # Laravel
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - app-network

  vite:
    image: node:18
    container_name: ims_laravel_vite
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: ["/bin/sh", "-c", "npm install && npm run dev"]
    ports:
      - "5173:5173"
    networks:
      - app-network
    depends_on:
      - app

  db:
    image: mysql:8
    container_name: ims_laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbims
      MYSQL_USER: user
      MYSQL_PASSWORD: ''
    ports:
      - "3306:3306"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ims_laravel_phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 500M
    ports:
      - "8080:80"
    networks:
      - app-network
    volumes:
      - ./phpmyadmin-custom.ini:/usr/local/etc/php/conf.d/custom.ini

networks:
  app-network:
    driver: bridge
