services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ims_laravel
    container_name: ims_laravel
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    networks:
      - app-network

  db:
    image: mysql:8
    container_name: ims_laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbims
      MYSQL_USER: user
      MYSQL_PASSWORD: ''
    ports:
      - "3306:3306"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ims_laravel_phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge